FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY src ./src

RUN mkdir -p /app/logs/hammer_radar

CMD ["python", "-m", "src.app.hammer_radar.main"]
