#!/usr/bin/env bash
set -euo pipefail

printf '%s\n' 'R295 PRINT ONLY - timer-observed armed-lane wait certificate plan'
printf '%s\n' ''
printf '%s\n' 'This script prints commands only. It does not run systemctl, curl, sudo, installs, deletes, copies, moves, Binance calls, or order endpoints.'
printf '%s\n' ''
printf '%s\n' '1. Timer health CLI check:'
printf '%s\n' 'PYTHONPATH=. .venv/bin/python -m src.app.hammer_radar.operator.inspect --log-dir logs/hammer_radar_forward tiny-live-autonomous-trigger-scheduler-timer-health'
printf '%s\n' ''
printf '%s\n' '2. R294 rehearsal status CLI check:'
printf '%s\n' 'PYTHONPATH=. .venv/bin/python -m src.app.hammer_radar.operator.inspect --log-dir logs/hammer_radar_forward tiny-live-dry-run-lane-arming-rehearsal --lane-key "BTCUSDT|44m|long|ladder_close_50_618" --operator-id local_operator --reason "R294 dry-run lane arming rehearsal only; no submit; no order."'
printf '%s\n' ''
printf '%s\n' '3. R295 certificate CLI check with explicit record flag:'
printf '%s\n' 'PYTHONPATH=. .venv/bin/python -m src.app.hammer_radar.operator.inspect --log-dir logs/hammer_radar_forward tiny-live-timer-observed-armed-lane-wait-certificate --lane-key "BTCUSDT|44m|long|ladder_close_50_618" --operator-id local_operator --reason "R295 timer-observed armed-lane wait certificate only; no submit; no order." --record-timer-observed-armed-lane-wait-certificate'
printf '%s\n' ''
printf '%s\n' '4. API status check:'
printf '%s\n' 'curl -sS http://127.0.0.1:8015/tiny-live/timer-observed-armed-lane-wait-certificate/status | jq .'
printf '%s\n' ''
printf '%s\n' '5. Final console check:'
printf '%s\n' 'curl -sS http://127.0.0.1:8015/tiny-live/final-console | jq .timer_observed_armed_lane_wait_certificate_panel'
printf '%s\n' ''
printf '%s\n' '6. Safety grep:'
printf '%s\n' 'grep -R "\"order_placed\": true\|\"binance_order_endpoint_called\": true\|\"binance_test_order_endpoint_called\": true\|\"submit_attempted\": true\|\"real_order_placed\": true\|\"final_command_available\": true\|\"submit_allowed\": true\|\"executable_payload_created\": true\|\"secrets_shown\": true\|\"live_execution_enabled\": true\|\"allow_live_orders\": true" -n logs/hammer_radar_forward/tiny_live*.ndjson logs/hammer_radar_forward/*autonomous*.ndjson logs/hammer_radar_forward/*binance*.ndjson 2>/dev/null || true'
printf '%s\n' ''
printf '%s\n' '7. Rollback/cleanup guidance:'
printf '%s\n' 'R295 writes only logs/hammer_radar_forward/tiny_live_timer_observed_armed_lane_wait_certificate.ndjson when the explicit record flag is used.'
printf '%s\n' 'For review cleanup, archive that repo-local R295 ledger record if desired. Do not delete shared runtime logs without operator approval.'
