#!/usr/bin/env bash
set -euo pipefail

printf '%s\n' 'R296 PRINT ONLY - test-only matching candidate trigger certificate plan'
printf '%s\n' ''
printf '%s\n' 'This script prints commands only. It does not run sudo, systemctl, curl, installs, deletes, copies, moves, Binance calls, or order endpoints.'
printf '%s\n' ''
printf '%s\n' '1. R295 wait certificate check:'
printf '%s\n' 'PYTHONPATH=. .venv/bin/python -m src.app.hammer_radar.operator.inspect --log-dir logs/hammer_radar_forward tiny-live-timer-observed-armed-lane-wait-certificate --lane-key "BTCUSDT|44m|long|ladder_close_50_618" --operator-id local_operator --reason "R295 wait certificate check before R296; no submit; no order."'
printf '%s\n' ''
printf '%s\n' '2. R296 matching simulation CLI command:'
printf '%s\n' 'PYTHONPATH=. .venv/bin/python -m src.app.hammer_radar.operator.inspect --log-dir logs/hammer_radar_forward tiny-live-test-only-matching-candidate-trigger-certificate --lane-key "BTCUSDT|44m|long|ladder_close_50_618" --operator-id local_operator --reason "R296 test-only matching candidate trigger certificate; no submit; no order." --simulate-matching-fresh-candidate-for-tests-only --record-test-only-matching-candidate-trigger-certificate'
printf '%s\n' ''
printf '%s\n' '3. R296 nonmatching simulation CLI command:'
printf '%s\n' 'PYTHONPATH=. .venv/bin/python -m src.app.hammer_radar.operator.inspect --log-dir logs/hammer_radar_forward tiny-live-test-only-matching-candidate-trigger-certificate --lane-key "BTCUSDT|44m|long|ladder_close_50_618" --operator-id local_operator --reason "R296 test-only nonmatching candidate no-trigger certificate; no submit; no order." --simulate-nonmatching-fresh-candidate-for-tests-only'
printf '%s\n' ''
printf '%s\n' '4. API status command:'
printf '%s\n' 'curl -sS http://127.0.0.1:8015/tiny-live/test-only-matching-candidate-trigger-certificate/status | jq .'
printf '%s\n' ''
printf '%s\n' '5. Final console command:'
printf '%s\n' 'curl -sS http://127.0.0.1:8015/tiny-live/final-console | jq .test_only_matching_candidate_trigger_certificate_panel'
printf '%s\n' ''
printf '%s\n' '6. Safety grep:'
printf '%s\n' 'grep -R "\"order_placed\": true\|\"binance_order_endpoint_called\": true\|\"binance_test_order_endpoint_called\": true\|\"submit_attempted\": true\|\"real_order_placed\": true\|\"final_command_available\": true\|\"submit_allowed\": true\|\"executable_payload_created\": true\|\"secrets_shown\": true\|\"live_execution_enabled\": true\|\"allow_live_orders\": true" -n logs/hammer_radar_forward/tiny_live*.ndjson logs/hammer_radar_forward/*autonomous*.ndjson logs/hammer_radar_forward/*binance*.ndjson 2>/dev/null || true'
printf '%s\n' ''
printf '%s\n' '7. Cleanup guidance:'
printf '%s\n' 'R296 writes only logs/hammer_radar_forward/tiny_live_test_only_matching_candidate_trigger_certificate.ndjson when the explicit R296 record flag is used.'
printf '%s\n' 'For review cleanup, archive that repo-local R296 ledger record if desired. Do not delete shared runtime logs without operator approval.'
