#!/usr/bin/env bash
set -euo pipefail

printf '%s\n' 'R297 PRINT ONLY - timer-integrated test-only matching trigger rehearsal plan'
printf '%s\n' ''
printf '%s\n' 'This script prints commands only. It does not run sudo, systemctl, curl, installs, deletes, copies, moves, Binance calls, or order endpoints.'
printf '%s\n' ''
printf '%s\n' '1. Timer health check:'
printf '%s\n' 'PYTHONPATH=. .venv/bin/python -m src.app.hammer_radar.operator.inspect --log-dir logs/hammer_radar_forward tiny-live-autonomous-trigger-scheduler-timer-health'
printf '%s\n' ''
printf '%s\n' '2. R296 certificate check:'
printf '%s\n' 'PYTHONPATH=. .venv/bin/python -m src.app.hammer_radar.operator.inspect --log-dir logs/hammer_radar_forward tiny-live-test-only-matching-candidate-trigger-certificate --lane-key "BTCUSDT|44m|long|ladder_close_50_618" --operator-id local_operator --reason "R296 check before R297; no submit; no order." --simulate-matching-fresh-candidate-for-tests-only'
printf '%s\n' ''
printf '%s\n' '3. R297 plain safe-default API check:'
printf '%s\n' 'curl -sS http://127.0.0.1:8015/tiny-live/timer-integrated-test-only-matching-trigger-rehearsal/status | jq .'
printf '%s\n' ''
printf '%s\n' '4. R297 explicit matching CLI rehearsal command:'
printf '%s\n' 'PYTHONPATH=. .venv/bin/python -m src.app.hammer_radar.operator.inspect --log-dir logs/hammer_radar_forward tiny-live-timer-integrated-test-only-matching-trigger-rehearsal --lane-key "BTCUSDT|44m|long|ladder_close_50_618" --operator-id local_operator --reason "R297 timer-integrated test-only matching trigger rehearsal; no submit; no order." --simulate-matching-fresh-candidate-for-tests-only --iterations 1 --record-timer-integrated-test-only-matching-trigger-rehearsal'
printf '%s\n' ''
printf '%s\n' '5. R297 explicit nonmatching CLI rehearsal command:'
printf '%s\n' 'PYTHONPATH=. .venv/bin/python -m src.app.hammer_radar.operator.inspect --log-dir logs/hammer_radar_forward tiny-live-timer-integrated-test-only-matching-trigger-rehearsal --lane-key "BTCUSDT|44m|long|ladder_close_50_618" --operator-id local_operator --reason "R297 timer-integrated test-only nonmatching no-trigger rehearsal; no submit; no order." --simulate-nonmatching-fresh-candidate-for-tests-only --iterations 1'
printf '%s\n' ''
printf '%s\n' '6. R297 explicit API simulation command:'
printf '%s\n' 'curl -sS "http://127.0.0.1:8015/tiny-live/timer-integrated-test-only-matching-trigger-rehearsal/status?simulate_matching_for_tests_only=true&lane_key=BTCUSDT%7C44m%7Clong%7Cladder_close_50_618" | jq .'
printf '%s\n' ''
printf '%s\n' '7. Final console check:'
printf '%s\n' 'curl -sS http://127.0.0.1:8015/tiny-live/final-console | jq .timer_integrated_test_only_matching_trigger_rehearsal_panel'
printf '%s\n' ''
printf '%s\n' '8. Safety grep:'
printf '%s\n' 'grep -R "\"order_placed\": true\|\"binance_order_endpoint_called\": true\|\"binance_test_order_endpoint_called\": true\|\"submit_attempted\": true\|\"real_order_placed\": true\|\"final_command_available\": true\|\"submit_allowed\": true\|\"executable_payload_created\": true\|\"secrets_shown\": true\|\"live_execution_enabled\": true\|\"allow_live_orders\": true" -n logs/hammer_radar_forward/tiny_live*.ndjson logs/hammer_radar_forward/*autonomous*.ndjson logs/hammer_radar_forward/*binance*.ndjson 2>/dev/null || true'
printf '%s\n' ''
printf '%s\n' '9. Cleanup guidance:'
printf '%s\n' 'R297 writes only logs/hammer_radar_forward/tiny_live_timer_integrated_test_only_matching_trigger_rehearsal.ndjson when the explicit R297 record flag is used.'
printf '%s\n' 'For review cleanup, archive that repo-local R297 ledger record if desired. Do not delete shared runtime logs without operator approval.'
