#!/usr/bin/env bash
set -euo pipefail

echo "R292 PRINT ONLY - installed dry-run timer unit refresh plan"
echo "This script prints commands only. It does not run sudo, systemctl, install, or rm."
echo ""
echo "# Refresh installed dry-run units after repo template update"
echo "sudo mkdir -p /tmp/hammer-r292-systemd-backup"
echo "sudo cp -a /etc/systemd/system/hammer-autonomous-trigger-scheduler-dry-run.service /tmp/hammer-r292-systemd-backup/hammer-autonomous-trigger-scheduler-dry-run.service"
echo "sudo cp -a /etc/systemd/system/hammer-autonomous-trigger-scheduler-dry-run.timer /tmp/hammer-r292-systemd-backup/hammer-autonomous-trigger-scheduler-dry-run.timer"
echo "sudo systemctl stop hammer-autonomous-trigger-scheduler-dry-run.timer"
echo "sudo install -m 0644 ops/systemd/hammer-radar/hammer-autonomous-trigger-scheduler-dry-run.service.template /etc/systemd/system/hammer-autonomous-trigger-scheduler-dry-run.service"
echo "sudo install -m 0644 ops/systemd/hammer-radar/hammer-autonomous-trigger-scheduler-dry-run.timer.template /etc/systemd/system/hammer-autonomous-trigger-scheduler-dry-run.timer"
echo "sudo systemctl daemon-reload"
echo "sudo systemctl start hammer-autonomous-trigger-scheduler-dry-run.timer"
echo ""
echo "# Status checks"
echo "systemctl status hammer-autonomous-trigger-scheduler-dry-run.timer --no-pager -l"
echo "systemctl list-timers hammer-autonomous-trigger-scheduler-dry-run.timer --no-pager --all"
echo "journalctl -u hammer-autonomous-trigger-scheduler-dry-run.service -n 120 --no-pager"
echo "PYTHONPATH=. .venv/bin/python -m src.app.hammer_radar.operator.inspect --log-dir logs/hammer_radar_forward tiny-live-autonomous-trigger-scheduler-timer-health | jq ."
echo "curl -sS http://127.0.0.1:8015/tiny-live/autonomous-trigger-scheduler/timer-health | jq ."
echo ""
echo "# Rollback commands"
echo "sudo systemctl stop hammer-autonomous-trigger-scheduler-dry-run.timer"
echo "sudo cp -a /tmp/hammer-r292-systemd-backup/hammer-autonomous-trigger-scheduler-dry-run.service /etc/systemd/system/hammer-autonomous-trigger-scheduler-dry-run.service"
echo "sudo cp -a /tmp/hammer-r292-systemd-backup/hammer-autonomous-trigger-scheduler-dry-run.timer /etc/systemd/system/hammer-autonomous-trigger-scheduler-dry-run.timer"
echo "sudo systemctl daemon-reload"
echo "sudo systemctl start hammer-autonomous-trigger-scheduler-dry-run.timer"
echo ""
echo "R292 safety: no submit, no order, no executable payload, no Binance order endpoint."
